inputs:
  WEDDING_NAME1: Sandra
  WEDDING_NAME2: Yann
  WEDDING_DATE: 10/10/2026
  VENUE_NAME: Grand Dax, dans les Landes
  VENUE_CIVIL: 14 rue Saint-Pierre, 40100 Dax
  VENUE_RECEPTION: 3A Rue Gustave Eiffel, 40180 Narrosse