name: Deploy

on:
  push:
    tags:
      - '*deploy*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/kira-app
            git pull origin kira
            docker build -t kira-app:latest .
            docker stop kira-app || true
            docker rm kira-app || true
            docker run -d \
              --name kira-app \
              --restart always \
              -p 127.0.0.1:8001:8080 \
              -v ~/kira-app/logs:/app/logs \
              --env-file .env \
              kira-app:latest
            docker image prune -f