name: Deploy

on:
  push:
    branches: [main]
    tags:
      - '*deploy*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying 
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/wedding-app
            git pull origin main
            docker build -t wedding-app:latest .
            docker stop wedding-app || true
            docker rm wedding-app || true
            docker run -d \
              --name wedding-app \
              --restart always \
              -p 127.0.0.1:8000:8000 \
              --env-file .env \
              wedding-app:latest